<?php

/**
 * @file
 * Contains migrate_barami.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_barami_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_barami module.
    case 'help.page.migrate_barami':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A custom migration to import from barami site.') . '</p>';
      return $output;

    default:
  }
}
